import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {chromium} from 'playwright-core';import {buildBrowserOptions} from './build_browser.mjs';import {loadBuildLibraries} from './build_vendor.mjs';
const root=path.resolve(import.meta.dirname,'..'),dist=path.join(root,'dist'),rows=[],cache=new Map();
const server=http.createServer((req,res)=>{let file=path.join(dist,decodeURIComponent(new URL(req.url,'http://local').pathname));if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file))return res.writeHead(404).end();res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(file).pipe(res);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch(await buildBrowserOptions()),libraries=await loadBuildLibraries();
const routes=fs.readdirSync('destinos/buzios',{recursive:true}).filter(f=>f==='index.html'||f.endsWith('/index.html')).map(f=>'/destinos/buzios/'+f.replace(/index.html$/,''));
fs.mkdirSync('/tmp/buzios-editorial-shots',{recursive:true});
try{for(const width of [1365,390]){
 const context=await browser.newContext({viewport:{width,height:900},isMobile:width===390,hasTouch:width===390});
 await context.route('**/*',async r=>{const u=r.request().url();if(new URL(u).origin===base)return r.continue();if(libraries.has(u))return r.fulfill({body:libraries.get(u),contentType:'text/javascript'});if(r.request().resourceType()==='image'){try{if(!cache.has(u))cache.set(u,fetch(u,{signal:AbortSignal.timeout(20000)}).then(async x=>{if(!x.ok)throw Error(x.status);return Buffer.from(await x.arrayBuffer());}));return r.fulfill({body:await cache.get(u),contentType:'image/jpeg'});}catch{return r.abort();}}return r.abort();});
 await context.addInitScript(()=>{window.__qa={cls:0,lcp:0};new PerformanceObserver(l=>l.getEntries().forEach(e=>{if(!e.hadRecentInput)window.__qa.cls+=e.value;})).observe({type:'layout-shift',buffered:true});new PerformanceObserver(l=>l.getEntries().forEach(e=>window.__qa.lcp=e.startTime)).observe({type:'largest-contentful-paint',buffered:true});});
 const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const route of routes)for(const language of ['ES','PT','EN']){
  errors=[];const prefix=language==='ES'?'':'/'+language.toLowerCase();await page.goto(base+prefix+route,{waitUntil:'domcontentloaded'});await page.evaluate(async()=>{for(const s of document.querySelectorAll('script[type="module"][src]')){const m=await import(s.src);if(m.ready)await m.ready;}});
  await page.evaluate(async()=>{for(const i of document.images){i.loading='eager';try{await i.decode();}catch{}}});
  const row=await page.evaluate(()=>({title:document.title,description:document.querySelector('meta[name="description"]')?.content,canonical:document.querySelector('link[rel="canonical"]')?.href,og:document.querySelector('meta[property="og:title"]')?.content,lang:document.documentElement.lang,h1:document.querySelectorAll('main h1').length,words:document.querySelector('main')?.innerText.split(/\s+/).length,broken:[...document.images].filter(i=>!i.naturalWidth).map(i=>i.src),alt:[...document.images].filter(i=>!i.alt).map(i=>i.src),overflow:document.documentElement.scrollWidth>innerWidth+1,links:[...document.querySelectorAll('#bz-app a[href]')].map(a=>a.getAttribute('href')),metrics:window.__qa}));
  row.editorial=await page.evaluate(()=>({beaches:document.querySelectorAll('.bz-visual-slot').length,detailPairs:document.querySelectorAll('.bz-editorial-details dt').length,zoneRows:document.querySelectorAll('.bz-matrix tbody tr').length,zoneColumns:document.querySelectorAll('.bz-matrix thead th').length-1}));
  row.route=route;row.language=language;row.width=width;row.errors=[...errors];row.missingLocalLinks=row.links.filter(h=>h.startsWith('/')&&!fs.existsSync(path.join(root,h.replace(/^\/(pt|en)(?=\/)/,'' ).split('#')[0].split('?')[0])));delete row.links;
  if(route.endsWith('/perfiles/')){await page.selectOption('#bz-profile-choice','1');row.profileVisible=await page.locator('#bz-section-0 .bz-card:visible').count();await page.selectOption('#bz-profile-choice','');}
  rows.push(row);if(language==='ES'&&['/destinos/buzios/','/destinos/buzios/perfiles/','/destinos/buzios/accesibilidad/','/destinos/buzios/compras/','/destinos/buzios/playas/','/destinos/buzios/alojamiento/'].includes(route))await page.screenshot({path:'/tmp/buzios-editorial-shots/'+route.split('/').filter(Boolean).at(-1)+'-'+width+'.png',fullPage:false});
  if(language==='ES'&&['/destinos/buzios/playas/','/destinos/buzios/alojamiento/'].includes(route)){await page.locator(route.endsWith('/playas/')?'.bz-editorial-details':'.bz-matrix-scroll').first().scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/buzios-editorial-shots/'+(route.endsWith('/playas/')?'beach-details':'zone-matrix')+'-'+width+'.png'});}
 }
 await context.close();console.log('checked width',width,rows.length);
}}finally{await browser.close();server.close();}
const failures=rows.filter(r=>r.errors.length||r.broken.length||r.alt.length||r.overflow||r.missingLocalLinks.length||(r.route.endsWith('/playas/')&&(r.editorial.beaches!==23||r.editorial.detailPairs!==207))||(r.route.endsWith('/alojamiento/')&&(r.editorial.zoneRows!==12||r.editorial.zoneColumns!==9))||r.h1!==1||!r.description||r.og!==r.title||r.lang!==({ES:'es',PT:'pt-BR',EN:'en'}[r.language])||(r.profileVisible&&r.profileVisible!==1));
const report={routes:routes.length,combinations:rows.length,failures:failures.length,performanceScope:'Local synthetic observations, with eager-image QA. Not field CWV or INP certification.',rows};fs.writeFileSync('docs/buzios/QA_EDITORIAL_RUNTIME.json',JSON.stringify(report,null,2));console.log(JSON.stringify({routes:routes.length,combinations:rows.length,failures},null,2));if(failures.length)process.exitCode=1;
