import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {chromium} from 'playwright-core';import {buildBrowserOptions} from './build_browser.mjs';import {loadBuildLibraries} from './build_vendor.mjs';
import {beachIndex} from '../assets/js/buzios-beach-v2-data.js';
const root=path.resolve(import.meta.dirname,'..'),dist=path.join(root,'dist'),rows=[],cache=new Map();
const server=http.createServer((req,res)=>{let file=path.join(dist,decodeURIComponent(new URL(req.url,'http://local').pathname));if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file))return res.writeHead(404).end();res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(file).pipe(res);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch(await buildBrowserOptions()),libraries=await loadBuildLibraries();
const routes=fs.readdirSync('destinos/buzios',{recursive:true}).filter(f=>f==='index.html'||f.endsWith('/index.html')).map(f=>'/destinos/buzios/'+f.replace(/index.html$/,''));
fs.mkdirSync('/tmp/buzios-editorial-shots',{recursive:true});
try{for(const width of [1365,390]){
 const context=await browser.newContext({viewport:{width,height:900},isMobile:width===390,hasTouch:width===390});
 await context.route('**/*',async r=>{const u=r.request().url();if(new URL(u).origin===base)return r.continue();if(libraries.has(u))return r.fulfill({body:libraries.get(u),contentType:'text/javascript'});if(r.request().resourceType()==='image'){try{if(!cache.has(u))cache.set(u,fetch(u,{signal:AbortSignal.timeout(20000)}).then(async x=>{if(!x.ok)throw Error(x.status);return Buffer.from(await x.arrayBuffer());}));return r.fulfill({body:await cache.get(u),contentType:'image/jpeg'});}catch{return r.abort();}}return r.abort();});
 await context.addInitScript(()=>{window.__qa={cls:0,lcp:0};new PerformanceObserver(l=>l.getEntries().forEach(e=>{if(!e.hadRecentInput)window.__qa.cls+=e.value;})).observe({type:'layout-shift',buffered:true});new PerformanceObserver(l=>l.getEntries().forEach(e=>window.__qa.lcp=e.startTime)).observe({type:'largest-contentful-paint',buffered:true});});
 const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const route of routes)for(const language of ['ES','PT','EN']){
  errors=[];const prefix=language==='ES'?'':'/'+language.toLowerCase();await page.goto(base+prefix+route,{waitUntil:'domcontentloaded'});await page.evaluate(async()=>{for(const s of document.querySelectorAll('script[type="module"][src]')){const m=await import(s.src);if(m.ready)await m.ready;}});
  await page.evaluate(async()=>{for(const i of document.images){i.loading='eager';try{await i.decode();}catch{}}});
  const row=await page.evaluate(()=>({title:document.title,description:document.querySelector('meta[name="description"]')?.content,canonical:document.querySelector('link[rel="canonical"]')?.href,og:document.querySelector('meta[property="og:title"]')?.content,lang:document.documentElement.lang,h1:document.querySelectorAll('main h1').length,words:document.querySelector('main')?.innerText.split(/\s+/).length,broken:[...document.images].filter(i=>!i.naturalWidth&&new URL(i.currentSrc||i.src,location.href).origin===location.origin).map(i=>i.currentSrc||i.src),remoteImages:[...new Set([...document.images].filter(i=>new URL(i.currentSrc||i.src,location.href).origin!==location.origin).map(i=>new URL(i.currentSrc||i.src,location.href).origin))],alt:[...document.images].filter(i=>!i.alt).map(i=>i.src),overflow:document.documentElement.scrollWidth>innerWidth+1,links:[...document.querySelectorAll('#bz-app a[href]')].map(a=>a.getAttribute('href')),metrics:window.__qa}));
  row.editorial=await page.evaluate(()=>({beaches:document.querySelectorAll('.bz-visual-slot').length,detailPairs:document.querySelectorAll('.bz-editorial-details dt').length,zoneCards:document.querySelectorAll('.bz-zone-card').length,zoneOpenCriteria:[...document.querySelectorAll('.bz-zone-card details')].reduce((n,d)=>n+d.querySelectorAll('dt').length,0)}));
  row.beachV2=await page.evaluate(()=>{const cards=[...document.querySelectorAll('.bz2-card')],steps=[...document.querySelectorAll('.bz2-story-step')],photos=[...document.querySelectorAll('.bz2-shell img')].map(i=>i.getAttribute('src'));return {cards:cards.length,cardCopyMax:Math.max(0,...cards.map(a=>a.querySelector('p')?.textContent.length||0)),cardPhotos:cards.filter(a=>a.querySelector('img')).length,cardPhotoDuplicates:cards.map(a=>a.querySelector('img')?.getAttribute('src')).filter(Boolean).length-new Set(cards.map(a=>a.querySelector('img')?.getAttribute('src')).filter(Boolean)).size,steps:steps.length,photoCount:photos.length,photoDuplicates:photos.length-new Set(photos).size,photoCredits:[...document.querySelectorAll('.bz2-photo img')].every(i=>i.closest('figure')?.querySelectorAll('figcaption a').length>=2),firstSequence:[...document.querySelector('.bz2-detail-intro + .bz2-story-wrap')?.children||[]].slice(0,2).map(e=>e.tagName+'.'+(e.className||'').toString().trim().replace(/\s+/g,'.')),collapsedLongCopy:[...document.querySelectorAll('.bz-card-more')].every(d=>!d.open)}});
  row.route=route;row.language=language;row.width=width;row.errors=[...errors];row.missingLocalLinks=row.links.filter(h=>h.startsWith('/')&&!fs.existsSync(path.join(root,h.replace(/^\/(pt|en)(?=\/)/,'' ).split('#')[0].split('?')[0])));delete row.links;
  if(route.endsWith('/perfiles/')){await page.selectOption('#bz-profile-choice','1');row.profileVisible=await page.locator('#bz-section-0 .bz-card:visible').count();await page.selectOption('#bz-profile-choice','');}
  rows.push(row);if(language==='ES'&&['/destinos/buzios/','/destinos/buzios/perfiles/','/destinos/buzios/accesibilidad/','/destinos/buzios/compras/','/destinos/buzios/playas/','/destinos/buzios/alojamiento/','/destinos/buzios/playas/geriba/'].includes(route))await page.screenshot({path:'/tmp/buzios-editorial-shots/'+route.split('/').filter(Boolean).slice(-1)[0]+'-'+width+'.png',fullPage:false});
  if(language==='ES'&&route==='/destinos/buzios/playas/'){await page.locator('.bz2-card').first().scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/buzios-editorial-shots/beach-hub-cards-'+width+'.png'});}
  if(language==='ES'&&route==='/destinos/buzios/playas/geriba/'){await page.locator('.bz2-story-identity').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/buzios-editorial-shots/beach-story-'+width+'.png'});}
  if(language==='ES'&&route==='/destinos/buzios/alojamiento/'){await page.locator('.bz-zone-atlas').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/buzios-editorial-shots/zone-atlas-'+width+'.png'});}
 }
 await context.close();console.log('checked width',width,rows.length);
}}finally{await browser.close();server.close();}
const photoOwners=new Map();for(const beach of beachIndex)for(const photo of beach.images||[]){if(photoOwners.has(photo))photoOwners.get(photo).push(beach.name);else photoOwners.set(photo,[beach.name]);}
const repeatedBeachPhotos=[...photoOwners].filter(([,owners])=>owners.length>1);
const missingBeachPhotos=beachIndex.filter(beach=>!(beach.images||[]).length).map(beach=>beach.name);
const localizedDescription=r=>r.route==='/destinos/buzios/playas/'?r.language==='PT'?r.description.startsWith('Praias de Búzios:'):r.language==='EN'?r.description.startsWith('Búzios beaches:'):true:r.route.startsWith('/destinos/buzios/playas/')&&r.route!=='/destinos/buzios/playas/'?r.language==='PT'?r.description.includes('Um guia editorial desta praia'):r.language==='EN'?r.description.includes('An editorial guide to this beach'):true:true;
const failures=rows.filter(r=>r.errors.length||r.broken.length||r.alt.length||r.overflow||r.missingLocalLinks.length||!localizedDescription(r)||(r.route==='/destinos/buzios/playas/'&&(r.beachV2.cards!==23||r.beachV2.cardCopyMax>142||r.beachV2.cardPhotoDuplicates!==0))||(r.route.startsWith('/destinos/buzios/playas/')&&!r.route.endsWith('/playas/')&&(r.beachV2.steps!==10||r.beachV2.photoDuplicates!==0||!r.beachV2.photoCredits||!['FIGURE','DIV.bz2-photo-pending'].some(v=>r.beachV2.firstSequence[0]?.includes(v))||!r.beachV2.firstSequence[1]?.includes('bz2-story-identity')))||(r.route==='/destinos/buzios/alojamiento/'&&(r.editorial.zoneCards!==12||r.editorial.zoneOpenCriteria!==108))||r.h1!==1||!r.description||r.og!==r.title||r.lang!==({ES:'es',PT:'pt-BR',EN:'en'}[r.language])||(r.profileVisible&&r.profileVisible!==1));
const report={routes:routes.length,combinations:rows.length,failures:failures.length,beaches:beachIndex.length,uniqueBeachPhotoFiles:photoOwners.size,repeatedBeachPhotos,missingBeachPhotos,remoteOriginsObserved:[...new Set(rows.flatMap(r=>r.remoteImages))],performanceScope:'Local synthetic observations, with eager-image QA. Not field CWV or INP certification. Remote image origins are recorded separately because this local QA sandbox cannot fetch them.',rows};fs.writeFileSync('docs/buzios/QA_EDITORIAL_RUNTIME.json',JSON.stringify(report,null,2));console.log(JSON.stringify({routes:routes.length,combinations:rows.length,failures:failures.length,beaches:beachIndex.length,uniqueBeachPhotoFiles:photoOwners.size,repeatedBeachPhotos,missingBeachPhotos},null,2));if(failures.length)process.exitCode=1;
