// Remove time-sensitive statements from existing nightlife guides and
// replace them with guidance to verify the event-specific official listing.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const chunkPath=path.join(root,'assets/js/translations/chunks/vida-nocturna-11.js');
const pages=[
 {route:'circo-voador',old:'Aquí siempre empiezo por la agenda. En septiembre de 2026 sigue con programación activa y próximos shows publicados para los meses siguientes. Puertas, precio y clasificación cambian en cada concierto, así que la ficha del evento es la referencia real.',es:'Aquí siempre empiezo por la agenda oficial. Consulta los conciertos próximos y abre la ficha de la fecha que te interesa: apertura de puertas, precio, clasificación y entradas pueden variar de un show a otro. Yo organizo el resto de la noche a partir de esa información, no de una programación antigua.',pt:'Eu sempre começo pela agenda oficial. Consulte os próximos shows e abra a página da data que interessa: abertura dos portões, preço, classificação etária e ingressos podem variar de um show para outro. Eu organizo o resto da noite com base nessa informação, não numa programação antiga.',en:'I always start with the official programme. Check upcoming concerts and open the listing for the date you want: door time, price, age rating and tickets can vary from one show to another. I plan the rest of the evening around that information, not an old listing.'},
 {route:'fundicao-progresso',old:'Aquí nunca usaría un horario genérico de discoteca. Primero miro el evento: apertura de puertas, sector, clasificación y ticket cambian. La agenda de septiembre de 2026 confirma actividad con shows, cine y otros formatos.',es:'Aquí nunca usaría un horario genérico de discoteca. Primero miro la agenda vigente y la ficha del evento: apertura de puertas, sector, clasificación y entradas cambian según la producción. La programación reúne formatos distintos —música, circo, danza, teatro y otras actividades—, así que compruebo qué se presenta durante mi visita.',pt:'Aqui eu nunca usaria um horário genérico de boate. Primeiro consulto a agenda vigente e a página do evento: abertura dos portões, setor, classificação etária e ingressos variam conforme a produção. A programação reúne formatos diferentes —música, circo, dança, teatro e outras atividades—, então confiro o que estará em cartaz durante minha visita.',en:'I would never use a generic nightclub schedule here. First I check the current programme and event listing: door time, section, age rating and tickets vary by production. The calendar includes different formats—music, circus, dance, theatre and other events—so I check what is on during my visit.'},
 {route:'feira-sao-cristovao-noite',old:'Puedes encontrar tapioca, carne de sol, baião de dois, queso coalho, dulces y bebidas regionales. De martes a jueves abre durante el día y la entrada suele ser gratuita, salvo feriados y eventos especiales. Viernes y sábado se extiende hasta la madrugada; el domingo cierra más temprano. La página oficial publica R$10 como valor habitual de viernes a domingo, con excepciones.',es:'Entre los sabores regionales puedes encontrar tapioca, carne de sol, baião de dois, queso coalho, dulces y bebidas. El horario y la entrada cambian según el día, los feriados y los eventos especiales: revisa la información oficial para la fecha elegida antes de organizar el traslado. No presupuestes la visita usando una tarifa antigua.',pt:'Entre os sabores regionais, você pode encontrar tapioca, carne de sol, baião de dois, queijo coalho, doces e bebidas. O horário e o ingresso variam conforme o dia, os feriados e os eventos especiais: consulte as informações oficiais para a data escolhida antes de organizar o deslocamento. Não planeje os gastos com base num valor antigo.',en:'Regional options include tapioca, carne de sol, baião de dois, queijo coalho, sweets and drinks. Opening times and admission vary by day, holidays and special events: check the official information for your chosen date before arranging transport. Do not budget the visit using an outdated price.'},
 {route:'lapa-40-graus',old:'Riotur publica apertura de miércoles a sábado desde las 18:00; el evento define el cierre y las condiciones. Antes de comprar, reviso quién toca, si hay lista, el precio del lote, la clasificación por edad y si existen áreas reservadas. La descripción general del local no reemplaza esos datos.',es:'La programación y el horario dependen de la fecha. Antes de comprar, reviso el anuncio vigente: quién toca, apertura, cierre previsto, lista, precio del lote, clasificación por edad y si hay áreas reservadas. La ficha general del local no reemplaza las condiciones del evento.',pt:'A programação e o horário dependem da data. Antes de comprar, confiro o anúncio vigente: quem vai tocar, abertura, previsão de encerramento, lista, preço do lote, classificação etária e se há áreas reservadas. A ficha geral da casa não substitui as condições do evento.',en:'The programme and schedule depend on the date. Before buying, I check the current listing: who is playing, doors, expected finish, guest list, ticket tier, age rating and whether reserved areas are available. The venue overview does not replace the event terms.'},
 {route:'pedra-do-sal',old:'Yo llegaría antes de que empiece la roda. Así puedes caminar por el Largo da Prainha, mirar la piedra y entender el territorio antes de que las calles se llenen. Las noches más conocidas son las de samba, especialmente lunes y viernes, pero la programación callejera cambia por clima, feriados y organización local.',es:'Yo llegaría con luz para caminar por el Largo da Prainha, mirar la piedra y entender el territorio antes de que las calles se llenen. Las rodas y encuentros al aire libre dependen de la programación y la organización local; confirma qué actividad está anunciada para tu fecha y ten en cuenta que el tiempo o los feriados pueden alterarla.',pt:'Eu chegaria ainda com luz para caminhar pelo Largo da Prainha, observar a pedra e entender o território antes de as ruas ficarem cheias. As rodas e os encontros ao ar livre dependem da programação e da organização local; confirme o que está anunciado para a sua data e lembre que o tempo ou feriados podem alterar o plano.',en:'I would arrive while it is still light to walk around Largo da Prainha, see the stone and understand the area before the streets fill up. Outdoor samba circles and gatherings depend on the local programme and organisers; check what is announced for your date and remember that weather or holidays may affect the plan.'},
 {route:'rio-scenarium',old:'La programación incluye samba de raíz, gafieira, chorinho y otros ritmos brasileños. El sábado tiene un plan diurno propio: la casa anuncia feijoada de 13:00 a 16:00 y música en vivo desde las 13:00. El almuerzo se vende por separado de la noche; revisa el menú y el ticket correctos.',es:'La programación incluye samba de raíz, gafieira, chorinho y otros ritmos brasileños. La casa anuncia un plan diurno de feijoada los sábados, separado de la programación nocturna. Confirma en la agenda vigente el horario, el menú, la entrada y si la reserva corresponde al almuerzo o al show de la noche: son experiencias distintas.',pt:'A programação inclui samba de raiz, gafieira, chorinho e outros ritmos brasileiros. A casa anuncia uma feijoada diurna aos sábados, separada da programação noturna. Confirme na agenda vigente o horário, o cardápio, o ingresso e se a reserva corresponde ao almoço ou ao show da noite: são experiências diferentes.',en:'The programme includes samba de raiz, gafieira, chorinho and other Brazilian rhythms. The venue advertises a daytime Saturday feijoada separately from its night programme. Check the current listing for the time, menu, admission and whether your booking is for lunch or the evening show: they are different experiences.'},
 {route:'trapiche-gamboa',old:'Yo llegaría con tiempo para recorrer Saúde y Pequena África antes del show. La apertura cambia según el día; viernes y sábado los shows empiezan más tarde. Riotur informa clasificación libre entre semana y 18+ los viernes y sábados. Confirma el evento y su hora antes de comprar o desplazarte.',es:'Yo llegaría con tiempo para recorrer Saúde y Pequena África antes del show. La apertura, la hora de la música y la clasificación por edad dependen de la programación: confirma la ficha del evento directamente con Trapiche antes de comprar o desplazarte, y revisa si hay un límite de edad para esa fecha.',pt:'Eu chegaria com tempo para percorrer Saúde e a Pequena África antes do show. A abertura, o horário da música e a classificação etária dependem da programação: confirme a página do evento diretamente com o Trapiche antes de comprar ou se deslocar e veja se há limite de idade para aquela data.',en:'I would arrive with time to explore Saúde and Pequena África before the show. Doors, music times and age ratings depend on the programme: check the event listing directly with Trapiche before buying or travelling, and confirm whether that date has an age limit.'}
];
let chunk=fs.readFileSync(chunkPath,'utf8');const additions=[];
for(const p of pages){
 const file=path.join(root,'vida-nocturna',p.route,'index.html');let html=fs.readFileSync(file,'utf8');
 if(!html.includes(p.old))throw new Error(`Expected original paragraph missing: ${p.route}`);
 html=html.replace(`<p>${p.old}</p>`,`<p>${p.es}</p>`);fs.writeFileSync(file,html);
 if(!chunk.includes(`${JSON.stringify(p.es)}:`))additions.push(`  ${JSON.stringify(p.es)}: {\n    "PT": ${JSON.stringify(p.pt)},\n    "EN": ${JSON.stringify(p.en)}\n  },`);
}
const end=chunk.lastIndexOf('};');if(end<0||chunk.slice(end+2).trim())throw new Error('Unexpected translation chunk format');
if(additions.length){const before=chunk.slice(0,end).trimEnd();chunk=before+(before.endsWith('}')?',':'')+'\n'+additions.join('\n')+'\n'+chunk.slice(end);fs.writeFileSync(chunkPath,chunk);}
const sourceRecords=[
 ['https://www.circovoador.com.br/','Circo Voador · official programme',['/vida-nocturna/circo-voador/'],'Current event listings and ticket availability; event-specific terms.'],
 ['https://www.feirasaocristovao.com/','Feira de São Cristóvão · official visitor information',['/vida-nocturna/feira-sao-cristovao-noite/'],'Current opening and admission information; terms can vary by date.'],
 ['https://www.fundicaoprogresso.com.br/','Fundição Progresso · official programme',['/vida-nocturna/fundicao-progresso/'],'Current programme and event-specific ticket details.'],
 ['https://riotur.rio/que_fazer/lapa-40/','Riotur · Lapa 40°',['/vida-nocturna/lapa-40-graus/'],'Venue identity and contact listing; event-level programme and schedule must be checked for the date.'],
 ['https://riotur.rio/que_fazer/pequena-africa/','Riotur · Pequena África itinerary',['/vida-nocturna/pedra-do-sal/'],'Historical and cultural context for Pedra do Sal; event details remain date-dependent.'],
 ['https://www.rioscenarium.com.br/','Rio Scenarium · official programme',['/vida-nocturna/rio-scenarium/'],'Current distinction between daytime feijoada and night shows.'],
 ['https://riotur.rio/en/que_fazer/trapiche-gamboa-2/','Riotur · Trapiche Gamboa',['/vida-nocturna/trapiche-gamboa/'],'Venue context; event-specific schedules and age terms should be checked with the venue.']
];
const out=path.join(root,'docs/rio/FUENTES_VIDA_NOCTURNA.json');let records=fs.existsSync(out)?JSON.parse(fs.readFileSync(out,'utf8')):[];
for(const [url,label,routes,use] of sourceRecords){const prior=records.find(x=>x.url===url);if(prior){prior.checked='2026-10-06';prior.routes=routes;prior.use=use;}else records.push({url,label,checked:'2026-10-06',routes,use,imageReusePermission:false});}
fs.writeFileSync(out,JSON.stringify(records,null,2)+'\n');
console.log(`Revalidated ${pages.length} existing nightlife passages and recorded ${sourceRecords.length} official sources.`);
