// Add concise stay-and-visit decisions to five high-priority Rio neighborhoods.
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const heading=['Dónde te conviene hacer base','Onde vale a pena se hospedar','Where to make your base'];
const entries={
 copacabana:[
  ['Para alojarte, mira la calle y la distancia a la estación además del precio. Frente a la orla tendrás paseo y ruido; más hacia dentro puedes ganar vida de barrio, pero revisa la cuesta, el cruce de avenidas y la caminata que harás con equipaje. Posto 4 es una referencia central, no el punto perfecto para todas las visitas. Yo elegiría por tu trayecto diario y sueño ligero.','Para se hospedar, observe a rua e a distância até a estação além do preço. Perto da orla você ganha passeio e pode ter mais ruído; mais para dentro, vida de bairro, mas confira ladeira, travessia de avenidas e a caminhada com malas. O Posto 4 é uma referência central, não o ponto perfeito para todo roteiro. Eu escolheria pelo deslocamento diário e pelo seu sono.','For a stay, look at the street and station distance as well as price. On the waterfront you get the promenade and may hear more noise; farther inland can feel more residential, but check hills, avenue crossings and the walk with luggage. Posto 4 is central, not perfect for every itinerary. I would choose based on daily travel and how lightly you sleep.'],
  ['Si vas a moverte entre Forte, Posto 2 y Leme, deja tiempo para la longitud de la playa: el nombre del barrio no te acerca automáticamente al acceso que buscas. Para una salida cultural, lluvia o compras, combina un solo sector con Metro y planifica la vuelta. Consejo EC: guarda en el mapa tu alojamiento, estación y cruce principal; Copacabana se disfruta más cuando dejas de medirla “a ojo”.','Se vai circular entre o Forte, Posto 2 e Leme, reserve tempo para a extensão da praia: o nome do bairro não deixa você automaticamente perto do acesso desejado. Para cultura, chuva ou compras, combine um trecho com o metrô e planeje a volta. Dica EC: salve no mapa hospedagem, estação e travessia principal; Copacabana fica mais fácil quando você não calcula “no olho”.','If you plan to move between the Fort, Posto 2 and Leme, allow time for the beach’s length: the neighbourhood name alone does not put you near the entrance you want. For culture, rain or shopping, pair one area with the Metro and plan your return. EC tip: pin your accommodation, station and main crossing; Copacabana is easier when you stop estimating it by eye.']
 ],
 ipanema:[
  ['Ipanema cambia bastante según el lado de la estación, el posto y la calle donde duermes. Si tu prioridad es playa, elige una calle transversal y confirma cuánto caminarás cargando cosas; si quieres cafés, tiendas y cenas, ubica primero esos planes y compara con el precio de alojamiento. Para grupos, manda el posto y la esquina, no sólo el nombre del barrio.','Ipanema muda bastante conforme o lado da estação, o posto e a rua onde você dorme. Se a prioridade é praia, escolha uma rua transversal e calcule a caminhada com suas coisas; se quer cafés, lojas e jantar, marque esses planos e compare com o preço da hospedagem. Para grupos, compartilhe posto e esquina, não apenas o nome do bairro.','Ipanema changes with the station side, posto and street where you stay. If the beach is the priority, choose a cross street and check how far you will walk with your things; if you want cafés, shops and dinner, pin those plans first and compare accommodation prices. For groups, share the posto and corner, not just the neighbourhood name.'],
  ['La combinación fácil es Arpoador más un tramo de Ipanema, pero sol, marea y multitudes modifican el ritmo. Una tarde en la arena puede convertirse en paseo y cena si el mar no acompaña. Para dormir, pregunta por ruido de la calle, aire acondicionado y acceso de noche; no es lo mismo quedar sobre una avenida activa que en una calle interior.','A combinação simples é Arpoador e um trecho de Ipanema, mas sol, maré e lotação mudam o ritmo. Uma tarde na areia pode virar passeio e jantar se o mar não ajudar. Para dormir, pergunte sobre ruído da rua, ar-condicionado e acesso à noite; uma avenida movimentada é diferente de uma rua interna.','An easy combination is Arpoador and a stretch of Ipanema, but sun, tide and crowds affect the pace. A beach afternoon can become a walk and dinner if the sea does not suit. Before booking, ask about street noise, air conditioning and night access; a busy avenue differs from an inland street.']
 ],
 leblon:[
  ['Leblon suele convenir a quien quiere un ritmo residencial, buenos restaurantes cerca y acceso a la playa, aceptando que la cuenta puede subir. Mira el trayecto hasta Antero de Quental o Jardim de Alah, no sólo la distancia en línea recta a la arena. Si tu plan principal es Centro, museos o vida nocturna en Lapa, compara el costo y el tiempo de viaje con otra base antes de reservar.','Leblon pode combinar com quem busca ritmo residencial, bons restaurantes por perto e praia, aceitando um custo maior. Confira o trajeto até Antero de Quental ou Jardim de Alah, não só a distância em linha reta até a areia. Se seu plano principal é Centro, museus ou noite na Lapa, compare custo e tempo de deslocamento com outra base antes de reservar.','Leblon may suit you if you want a residential pace, restaurants nearby and beach access, and are comfortable with a higher bill. Check the route to Antero de Quental or Jardim de Alah, not just straight-line distance to the sand. If your main plans are Centro, museums or Lapa nightlife, compare travel time and cost with another base before booking.'],
  ['Yo lo combinaría con Ipanema por tramos, no como obligación de recorrer toda la costa. En días de calor el paseo largo puede cansar más de lo que parece; en lluvia, arma un plan de café, comida o cultura bajo techo. Para cenar, pregunta por reserva y regreso, especialmente si tu alojamiento queda lejos del Metro.','Eu combinaria com Ipanema por trechos, sem transformar a orla inteira numa obrigação. Em dias quentes, uma caminhada longa pode cansar mais do que parece; com chuva, planeje café, comida ou cultura em local coberto. Para jantar, confira reserva e volta, especialmente se a hospedagem ficar longe do metrô.','I would pair it with Ipanema in sections, not make the entire waterfront a checklist. On hot days, a long walk can be more tiring than it looks; in rain, plan a café, meal or indoor culture stop. For dinner, check reservations and your return, especially if you are staying far from the Metro.']
 ],
 botafogo:[
  ['Botafogo te da una base más urbana: Metro, restaurantes, tiendas y conexiones, con una mezcla de calles residenciales y avenidas movidas. Al reservar, comprueba el ruido nocturno y el trayecto a pie a la estación; dos alojamientos con la misma etiqueta de barrio pueden sentirse muy distintos. La vista a la bahía es un paseo bonito, no una garantía de baño.','Botafogo oferece uma base mais urbana: metrô, restaurantes, lojas e conexões, com ruas residenciais e avenidas movimentadas. Ao reservar, confira ruído noturno e caminhada até a estação; duas hospedagens no mesmo bairro podem ter experiências bem diferentes. A vista da baía é um passeio bonito, não garantia de banho.','Botafogo gives you a more urban base: Metro, restaurants, shops and connections among residential streets and busy avenues. When booking, check night noise and the walk to the station; two stays in the same neighbourhood can feel very different. The bay view makes a lovely walk, not a guarantee for swimming.'],
  ['Urca, Flamengo, Centro y Copacabana son combinaciones naturales, pero el tiempo depende del tráfico y del lado de la bahía al que vas. Para una noche, decide antes dónde cenar y cómo regresar; la estación ayuda, aunque no sustituye revisar el último tramo. Si llueve, Botafogo suele funcionar mejor como base para alternar comida, cine o museo que como día de playa.','Urca, Flamengo, Centro e Copacabana são combinações naturais, mas o tempo depende do trânsito e do lado da baía. Para sair à noite, escolha onde jantar e como voltar; o metrô ajuda, mas não substitui conferir o trecho final. Com chuva, Botafogo pode funcionar melhor como base para comida, cinema ou museu do que como dia de praia.','Urca, Flamengo, Centro and Copacabana pair naturally, but travel time depends on traffic and which side of the bay you are heading to. For a night out, choose dinner and your return plan in advance; the Metro helps but does not replace checking the last leg. In rain, Botafogo may work better as a base for food, cinema or a museum than a beach day.']
 ],
 centro:[
  ['El Centro funciona muy bien si tu viaje gira alrededor de patrimonio, museos, negocios o conexiones; de noche y en fines de semana tiene otro pulso que un barrio residencial. Antes de reservar, confirma qué calles quedan activas a la hora que vuelves y la distancia a una estación o transporte. Yo lo elegiría por agenda y presupuesto, no por asumir que todo queda a un paseo corto.','O Centro funciona bem se sua viagem gira em torno de patrimônio, museus, trabalho ou conexões; à noite e nos fins de semana tem outro ritmo que um bairro residencial. Antes de reservar, confira quais ruas ficam movimentadas no horário de volta e a distância até estação ou transporte. Eu escolheria pela agenda e orçamento, não por achar que tudo fica a poucos passos.','Centro works well when your trip centres on heritage, museums, work or transport links; nights and weekends feel different from a residential neighbourhood. Before booking, check which streets are active when you return and the distance to transit. I would choose it for itinerary and budget, not assume everything is a short walk away.'],
  ['Agrupa Praça XV, Cinelândia, Lapa y la zona portuaria por sectores; el mapa no siempre muestra el tiempo de cruzar avenidas o entrar a un museo. En lluvia, un día cultural gana sentido, pero revisa aperturas y entradas. Para familia o movilidad reducida, prioriza trayectos concretos con sombra, baños y pausas. Al acabar la visita, acuerda el punto exacto del coche o VLT.','Agrupe Praça XV, Cinelândia, Lapa e a região portuária por trechos; o mapa nem sempre mostra o tempo de atravessar avenidas ou entrar num museu. Com chuva, um dia cultural faz sentido, mas confira abertura e ingressos. Com família ou mobilidade reduzida, priorize percursos específicos com sombra, banheiro e pausas. Ao terminar, combine o ponto exato do carro ou VLT.','Group Praça XV, Cinelândia, Lapa and the port area into separate stretches; a map may not show crossing time or museum entry queues. A rainy day can suit culture, but check openings and tickets. With family or reduced mobility, choose specific routes with shade, toilets and breaks. Agree on the exact car or VLT pickup point before leaving.']
 ]
};
const labels={
 heading,
 links:['Abrir la guía de transporte →','Abrir o guia de transporte →','Open the transport guide →'],
 sourceNote:['Consejo local de planificación; los horarios, el ruido, los precios y la operación pueden cambiar según la calle y la fecha.','Dica local de planejamento; horários, ruído, preços e funcionamento podem mudar conforme a rua e a data.','Local planning advice; hours, noise, prices and operations can vary by street and date.']
};
const phrases={};
function add(es,pt,en){phrases[es]={PT:pt,EN:en};}
add(...labels.heading);add(...labels.links);add(...labels.sourceNote);
for(const [slug,paragraphs] of Object.entries(entries))for(const triplet of paragraphs)add(...triplet);
const chunk=path.join(root,'assets/js/translations/chunks/barrios-02.js');
let dictionary=fs.readFileSync(chunk,'utf8');
const missing=Object.fromEntries(Object.entries(phrases).filter(([key])=>!dictionary.includes(JSON.stringify(key)+':')));
if(Object.keys(missing).length)dictionary=dictionary.replace('export default {',`export default {${JSON.stringify(missing).slice(1,-1)},`,1);
fs.writeFileSync(chunk,dictionary);
for(const [slug,paragraphs] of Object.entries(entries)){
 const file=path.join(root,'barrios',slug,'index.html');let html=fs.readFileSync(file,'utf8');
 const id='RIO_NEIGHBORHOOD_DEPTH_V1';
 const block=`<!-- ${id} --><article class="bh-card" data-rio-neighborhood-v1><h2>${labels.heading[0]}</h2>${paragraphs.map(p=>`<p>${p[0]}</p>`).join('')}<p><a href="../../transportes/">${labels.links[0]}</a></p></article><!-- /${id} -->`;
 if(html.includes(`<!-- ${id} -->`))html=html.replace(new RegExp(`<!-- ${id} -->[\\s\\S]*?<!-- \\/${id} -->`),block);
 else html=html.replace('<p class="bh-source-note">',block+'<p class="bh-source-note">');
 fs.writeFileSync(file,html);
 console.log('Neighborhood depth: /barrios/'+slug+'/');
}
